---
title: "Import and prepare swe eel data"
author: "Viktor Thunell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    embed-resources: true
    fig-width: 8
knitr: 
  opts_chunk:
    fig.align: center
editor: source
execute: 
  echo: true
  eval: true
  cache: false
---

## Introduction 


## Load libraries
  
```{r libs}
#| message: false

pkgs <- c("tidyverse", "devtools","tidylog","stacomiR","stacomirtools","broom",
 "purrr","janitor","patchwork","DBI","odbc","arrow","sf","sdmTMB","GGally")


if(length(setdiff(pkgs, rownames(installed.packages()))) > 0){
  install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
}

invisible(lapply(pkgs, library, character.only = T))

# # Source code for map plots
devtools::source_url("https://raw.githubusercontent.com/VThunell/diasp-lht/main/R/functions/map-plot.R") 

# source Eiriks conversion scripts and Durif stage scripts
source(file = "/Users/vitl0001/Documents/Projects/SWEel-lhts/script-functions-thawedsizes.R")
source(file = "/Users/vitl0001/Documents/Projects/SWEel-lhts/script-functions-durif.R")

options(ggplot2.continuous.colour = "viridis")
theme_set(theme_minimal()) 

# Set path
home <- here::here()

```

## Get data

### Sötebasen

Correct for thawing / ethanol Using E. Ryvoll-Åsheims functions based on Sundin et al. 2019. Do some renaming and calculate teh Durif index baed on Eirks Ryvoll-Åsheims script for that

```{r}
# import data and convert 
sb_ind <- read.delim("/Users/vitl0001/Documents/Projects/SWEel-lhts/data/ÅlindividerSötebasen.csv", sep=";", dec=",", fileEncoding="Latin1") %>% convert_alsotebasen_thawed_sizes()

colnames(sb_ind)

# sb_ind2 %>%
#   mutate(sex = if_else(sex %in% c("m","f"), 1, NA)) %>%
#   filter(is.na(sex)) %>%
#   summarise(n(), .by(Plats)
#   distinct(Plats)

sb_ind2 <- sb_ind %>%
  rename(length = Längd_corr,
         weight = Vikt_corr,
         age = Ålder,
         sex = Kön,
         visual_stage = Stadium
         ) %>%
  filter(!(is.na(length) & is.na(weight) & Åldersprov == "Nej")) %>%
  rowwise() %>%
  # get the eye diameter and pectoral fin measurement and take the mean to make sure we use all individuals that have a meassuremnt.
  mutate(diameter_eye = mean(c(VäD_corr,HöD_corr), na.rm = TRUE),
         length_pectoral = mean(c(HöBr_corr,VäBr_corr), na.rm = TRUE),
         diameter_eye = if_else(is.nan(diameter_eye),NA,diameter_eye),
         length_pectoral = if_else(is.nan(length_pectoral),NA,length_pectoral)) %>%
  ungroup() %>%
  # Fix coordinates. These uses "." as dec
  mutate(across(c(WGS84_E_Vatten, WGS84_N_Vatten, WGS84_N_Plats, WGS84_E_Plats), readr::parse_number),
         # when Plats coords are missing, we use the Vatten name. ~800 eels lacks coords but many of h
         lon = if_else(is.na(WGS84_E_Plats), WGS84_E_Vatten, WGS84_E_Plats),
         lat = if_else(is.na(WGS84_N_Plats), WGS84_N_Vatten, WGS84_N_Plats),
         db = "sb",
         year = if_else(Årtal1 == Årtal2, Årtal1, year(as_date(FångstDatum)))
         
         ) %>%
  # calculate Durif according to Eirik Ryvoll-Åsheims script
  mutate(durif_stage = stage_durif(length,weight,diameter_eye,length_pectoral,descr=F))
  
```


#### Durif vs Visual
```{r}
# check how durif correspond to visual
sb_ind2 %>% summarise(n = n(), .by = c(durif_stage,visual_stage)) %>% arrange(-n)
  
# check densities of durif stages vs visual for females
# lump/condense stages
sb_ind2 %>%
  drop_na(durif_stage,visual_stage,sex) %>%
  filter(sex %in% c("f"),
         visual_stage %in% c("Blankål","Halvblank ål","Gulål")) %>%
  mutate(redDurif_stage = case_when(durif_stage %in% c("I","FII","MII") ~ "I, MII & FII",
                                    durif_stage %in% c("FIII") ~ "FIII",
                                    durif_stage %in% c("FIV","FV") ~ "FIV & FV",
                                    #durif_stage %in% c("I") & sex == "m" ~ "m<3",
                                    .default = durif_stage)) %>%
  #summarise(n = n(), .by = c(durif_stage,visual_stage)) %>% arrange(visual_stage) %>%
  ggplot() +
  geom_density(aes(length, color = redDurif_stage), alpha = 0.5) +
  geom_density(aes(length, fill = visual_stage), color = NA, alpha = 0.2) 
  

```

### KUL

```{r}
# Connect to SLU-server:
# AQ_con <- dbConnect(odbc(),
#                     Driver = "ODBC Driver 18 for SQL Server",
#                     Server = "aquadw_prod.db.slu.se",
#                     USER = "vitl0001", # set you name
#                     Database = "AquaDW_prod",
#                     Trusted_Connection = "yes",
#                     Encrypt = "no",
#                     encoding = "utf-8")
#  
# # Extract the table with all individual eel data.
#  
# KUL <- dbGetQuery(AQ_con,"select * from AquaDW_prod.mart.KUL_INDIVID_NEW where Art = 'Ål'")
# saveRDS(KUL, file = paste0( "/Users/vitl0001/Documents/Projects/SWEel-lhts/data/KUL_",Sys.Date(),".RData"))
kul_ind <- readRDS("/Users/vitl0001/Documents/Projects/SWEel-lhts/data/KUL_2026-05-04.RData")

colnames(kul_ind)

kul_ind2 <- kul_ind %>% 
  filter(!(is.na(Slutlängd_cm) & is.na(Totalvikt_gram) & is.na(Ålder))) %>%
  rename(length = Slutlängd_mm,
         weight = Totalvikt_gram,
         age = Ålder,
         sex = Kön,
         visual_stage = Artbestämning,
         year = Fiskeår
         ) %>%
  mutate(lon = Bäst_longitud_decimal_grader,
         lat = Bäst_latitud_decimal_grader,
         db = "kul")

```
<!-- Error in `dbConnect()`: -->
<!-- ! ODBC failed with error 00000 from [unixODBC][Driver Manager]. -->
<!-- ✖ Can't open lib 'SQL Server' : file not found -->
<!-- ℹ From nanodbc/nanodbc.cpp:1184. -->
<!-- Run `rlang::last_trace()` to see where the error occurred. -->


## Join data and fix errors
```{r}
# can there be dupes between the dbs?
# dupes <- c(kul_ind2$Ind_id,sb_ind2$IndividID)[duplicated(c(kul_ind2$Ind_id,sb_ind2$IndividID))]
# kul_ind2 %>%
#   filter(Ind_id %in% dupes) %>% select(length,age,db) %>% bind_cols(sb_ind2 %>% filter(IndividID %in% dupes) %>% select(length,age,db)) # likely not

# join the sb and kul data
cols <- c("length","weight","age","lat","lon","sex","visual_stage","durif_stage","db","year")
df <- sb_ind2 %>% 
  select(all_of(cols), VattenNamn,diameter_eye,length_pectoral) %>% 
  bind_rows(kul_ind2 %>% 
            mutate(durif_stage = NA) %>%
            select(all_of(cols), Lokal)) %>%
  mutate(sex = ifelse(sex %in% c("f","Hona"), "female", 
                      if_else( sex %in% c("m","Hane"), "male", NA)),
         ind_id = row_number()) %>%
  # set one weight == 0 to NA
  mutate(weight = if_else(weight == 0, NA, weight))

# id. weird looking data based on le cren, eye diam and pectoral length
ab <- df %>%
  drop_na(weight,length) %>%
  lm(data = ., log(weight) ~ log(length)) %>%
  tidy() 
ap <- df %>%
  drop_na(length_pectoral,length) %>%
  lm(data = ., log(length_pectoral) ~ log(length)) %>%
  tidy() 

ol <- df %>%
  drop_na(weight,length,length_pectoral) %>%
  filter(!weight == 0) %>%
  mutate(a = ab$estimate[1], 
         b = ab$estimate[2],
         bp = ap$estimate[2],
         ap = ap$estimate[1]) %>%
  mutate(lecren = exp(a + b*log(length))/weight,
         pecindex = exp(ap + bp*log(length))/length_pectoral
         ) %>%
  mutate(lc_outlie = if_else(lecren < quantile(lecren, 0.00025) | lecren > quantile(lecren, 0.99975),1,0),
         pi_outlie = if_else(pecindex < quantile(pecindex, 0.000025),1,0))

#pec and lecren outlier
ol %>%
  ggplot() + 
  geom_point(aes(length,weight, color = factor(lc_outlie))) +
ol %>%
  ggplot() +
  geom_point(aes(length,length_pectoral, color = factor(pi_outlie)))

# odd data on eye diam 
df %>%
  drop_na(diameter_eye) %>%
  mutate(outlie = if_else(diameter_eye > 200,1,0)) %>%
  ggplot() + 
  geom_point(aes(length,diameter_eye, color = factor(outlie)))

# remove or change value of these outilers in the data
col <- ol %>% filter(lc_outlie == 1) %>% pull(ind_id)
pol <- ol %>% filter(pi_outlie == 1) %>% pull(ind_id)

df2 <- df %>% 
  mutate(diameter_eye = if_else(diameter_eye > 200,NA,diameter_eye)) %>%
  mutate(length_pectoral = if_else(ind_id %in% pol,NA,length_pectoral)) %>%
  filter(!ind_id %in% col) 

```

## Retrieve spatial info

```{r}
# make data spatial object
df_sf <- st_as_sf(df2 %>% drop_na(lat,lon), coords = c("lon", "lat"), crs = 4326,  remove = FALSE)

re <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/refeel/", format = "parquet")
ca <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/catchments/", format = "parquet")

# coastal polygon and sea basin (Norra/Södra Östersjön, Bottenviken, Västerhavet). From https://www.dataportal.se/datasets/78_7502.
read_sf("/Users/vitl0001/Documents/Projects/SWEel-lhts/Havsomraden_2016/Havsomraden_2016.shp") %>%
  st_transform(dst = 4326) %>%
  group_by(TYP_NFS06) %>%
  #distinct()
  ggplot() +
  geom_sf(aes(fill = TYP_NFS06), color =NA, show.legend = FALSE)

# basins
ba_sf <- read_sf("/Users/vitl0001/Documents/Projects/SWEel-lhts/Havsomraden_2016/Havsomraden_2016.shp") %>%
  st_transform(dst = 4326) %>%
  group_by(COMP_AUTH) %>%
  summarise() %>%
  ungroup() %>%
  rename(sea_basin = COMP_AUTH) %>%
  # rename the NA polygon to get fix these later
  mutate(sea_basin = if_else(is.na(sea_basin), "FIX", sea_basin))

# sea areas
sa_sf <- read_sf("/Users/vitl0001/Documents/Projects/SWEel-lhts/Havsomraden_2016/Havsomraden_2016.shp") %>%
  st_transform(dst = 4326) %>%
  group_by(TYP_NFS06) %>%
  summarise() %>%
  ungroup() %>%
  rename(sea_area = TYP_NFS06) %>%
  filter(!sea_area == "Ingår ej i typningen")
  
# refeel countries
co_sf <- re %>%
  collect() %>%
  filter(are_lev_code %in% "Country") %>%
  mutate(geometry = st_as_sfc(geom_polygon), crs = 4326) %>%
  st_as_sf(sf_column_name = "geometry", crs = 4326)

# catchments hydrosheds
ca_sf <- ca %>%
  collect() %>%
  mutate(geometry = st_as_sfc(shape, EWKB = TRUE, crs = 4326),
         main_catch = main_bas) %>%
  st_as_sf(sf_column_name = "geometry") %>%
  select(main_catch) %>%
  group_by(main_catch) %>%
  summarise() %>%
  ungroup()

# HAROs lookup
haros <- read_sf("/Users/vitl0001/Documents/Projects/SWEel-lhts/Huvudavrinnigsomrade shapefile/HARO.shp") 

haro_lookup <- ca_sf %>% 
  st_transform(3006) %>% 
  select(main_catch) %>%
  st_join(haros %>% st_transform(3006) %>%
            st_centroid() %>% select(text)) %>%
  st_drop_geometry() %>%
  distinct(text,main_catch) %>%
  drop_na(text)
  rename(haro = text) 

# add look up to hydrosheds
ca_sf <- ca_sf %>%
  left_join(haro_lookup)
#save for plotting
saveRDS(ca_sf, paste0(home,"/R/prep_data/joined_polygons.rds"))

# get basin and sea_area of each main catchment to join in sea_basin via catchment instead of coordinate
ca_sb <- ca %>%
  collect() %>%
  mutate(geometry = st_as_sfc(shape, EWKB = TRUE, crs = 4326),
         main_catch = main_bas) %>%
  filter(next_down == 0) %>%
  st_as_sf(sf_column_name = "geometry") %>%
  st_join(ba_sf %>% st_transform(4326), st_nearest_feature) %>%
  st_drop_geometry() %>%
  select(main_catch,sea_basin)
  
plot_map_Nord +
  geom_sf(data = ca_sf, aes(fill = main_catch), fill = "blue", color = NA,  alpha = 0.3) +
  geom_sf(data = haros, aes(), fill = "yellow",  alpha = 0.3, color = NA) +
plot_map_Nord +
  geom_sf(data = ca_sf, aes(), fill = "blue", linewidth = 0.2, alpha = 0.3) +
  labs(title = "hydrosheds (diaspara)") +
plot_map_Nord +
  geom_sf(data = haros, aes(), fill = "yellow",  linewidth = 0.2, alpha = 0.3) +
  labs(title = "smhi haros")

# join in country info and drop non SE data points
df_co <- df_sf %>%
  st_join(co_sf %>% select(are_code), join = st_nearest_feature) %>%
  rename(country = are_code) %>%
  filter(country == "SE")

# set marine to those that intersects with the basins and join in sea_area
df_coba <- df_co %>%
  st_join(ba_sf %>% st_transform(4326), join = st_intersects) %>%
  mutate(marine = if_else(is.na(sea_basin), "no", "yes")) %>%
  select(-sea_basin) 

# one obs is outside the marine defined by the marine polygon 
plot_map_Nord +
  geom_point(data = df_coba %>% st_drop_geometry() %>% add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000, color = marine), size = 0.1)
# make this marine
df_coba <- df_coba %>%
  mutate(marine = if_else(lat < 56 & lon > 15, "yes", marine))

# assign basin and sea area to marine individuals but exclude the FIX basin and use st_nearest_feature
df_coba_mar <- df_coba %>%
  filter(marine == "yes") %>%
  st_join(ba_sf %>% 
            filter(!sea_basin == "FIX") %>%
            st_transform(4326), join = st_nearest_feature) %>%
  st_join(sa_sf %>% st_transform(4326), join = st_nearest_feature)

plot_map_Nord +
  geom_point(data = df_coba_mar %>% st_drop_geometry() %>% add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000, color = sea_area, shape = sea_basin), size = 0.5, alpha = 0.1)

# add in catchments and basin to inland individuals (not caught in marine areas)
df_cobaca_inland <- df_coba %>%
  filter(marine == "no") %>% 
  st_join(ca_sf, join = st_nearest_feature) %>%
  st_drop_geometry() %>%
  left_join(ca_sb)

# join the inland and marine spatial units data
df_all <- df_cobaca_inland %>%
  mutate(spat.unit = as.character(main_catch)) %>%
  bind_rows(df_coba_mar %>%
              # For coastal spatial spatial units 
              #mutate(spat.unit = as.character(sea_basin))) %>% 
              mutate(spat.unit = sea_area)) %>%
  as_tibble() %>%
  left_join(haro_lookup, join_by(main_catch == main_catch))

```

## Data points in spatial units, catchments and basins
```{r}
plot_map_Nord +
  geom_sf(data = ca_sf %>% filter(main_catch %in% df_cobaca_inland$main_catch), aes(fill = factor(haro)), color = NA,  alpha = 0.8) +
  geom_point(data = df_all %>% 
  #filter(is.na(spat.unit)) %>%
               add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000, color = factor(spat.unit)) , size = 0.1, ) +
  labs(caption = "color is spatial unit")

plot_map_Nord +
  #geom_sf(data = ca_sf %>% filter(main_catch %in% df_cobaca_inland$main_catch), aes(fill = factor(main_catch)), color = NA,  alpha = 0.3)  +
  geom_point(data = df_all %>%
               mutate(Habitat = if_else(marine == "no", "Inland", "Marine")) %>%
               #filter(spat.unit == "Ö Sydkustens kustvatten" | is.na(spat.unit)) %>%
               add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000, color = Habitat), size = 0.1) +
  guides(color = guide_legend(title.position = "top")) +
  labs(color = "") +
  theme(legend.position = "inside", legend.position.inside = c(0.18, 0.80))

```

## Save data
```{r}
saveRDS(df_all %>% st_drop_geometry(), file = paste0(home, "/data/sweel_data_",Sys.Date(),".RData"))
```

