---
title: "Import and prepare eel data"
author: "Viktor Thunell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    embed-resources: true
    fig-width: 8
knitr: 
  opts_chunk:
    fig.align: center
editor: source
execute: 
  echo: true
  eval: true
  cache: false
---

## Introduction 


## Load libraries
  
```{r libs}
#| message: false

pkgs <- c("tidyverse", "devtools","tidylog","stacomiR","stacomirtools",
 "purrr","janitor","patchwork","DBI","odbc","arrow","sf","sdmTMB")


if(length(setdiff(pkgs, rownames(installed.packages()))) > 0){
  install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
}

invisible(lapply(pkgs, library, character.only = T))

# # Source code for map plots
devtools::source_url("https://raw.githubusercontent.com/VThunell/diasp-lht/main/R/functions/map-plot.R") # message of SHA-1 hash for file

options(ggplot2.continuous.colour = "viridis")
theme_set(theme_minimal()) 
# Set path
home <- here::here()

```
## Get data

### Sötebasen

```{r}
sb_ind <- read.delim("/Users/vitl0001/Documents/Projects/SWEel-lhts/data/ÅlindividerSötebasen.csv", sep=";", dec=",", fileEncoding="Latin1")

colnames(sb_ind)

sb_ind2 <- sb_ind %>%
  filter(!(is.na(Längd1) & is.na(Längd2) & is.na(Vikt2) & is.na(Vikt2) & Åldersprov == "Nej")) %>%
  rename(length1 = Längd1,
         length2 = Längd2,
         weight1 = Vikt1,
         weight2 = Vikt2,
         age = Ålder,
         sex = Kön,
         visual_stage = Stadium
         ) %>%
  # These uses "." as dec
  mutate(across(c(WGS84_E_Vatten, WGS84_N_Vatten, WGS84_N_Plats, WGS84_E_Plats), readr::parse_number),
         # when Plats coords are missing, we use the Vatten name. ~800 eels lacks coords
         lon = if_else(is.na(WGS84_E_Plats), WGS84_E_Vatten, WGS84_E_Plats),
         lat = if_else(is.na(WGS84_N_Plats), WGS84_N_Vatten, WGS84_N_Plats),
         db = "sb",
         year = if_else(Årtal1 == Årtal2, Årtal1, year(as_date(FångstDatum)))
         )
  
# Calculate Durif index for sb individuals where info on eye width and fin length exist, return NA for when that info is missing. Results in a vector with corresponding sb_ind2 row-numbers
D_ph <- sb_ind2 %>%
  rename(BL = length1,
         W = weight1,
         Dv = VäV,
         Dh = VäH,
         FL = VäBr) %>%
  select(BL,W,Dv,Dh,FL) %>%
  as.matrix() %>%
  stacomiR::fun_stage_durif() %>%
  tibble(Durif_stage = .) %>%
  mutate(row_id = row_number()) 

# join in Durif stage index 
sb_ind3 <- sb_ind2 %>%
  mutate(row_id = row_number()) %>%
  left_join(D_ph, join_by(row_id))
```

#### Durif vs Visual
```{r}
# check how durif correspond to visual
sb_ind3 %>% summarise(n = n(), .by = c(Durif_stage,visual_stage)) %>% arrange(-n)
  
# check densitoes of durif stages vs visual for females
# lump/condense stages
sb_ind3 %>%
  distinct(Durif_stage)
  drop_na(Durif_stage,visual_stage,sex) %>%
  filter(sex %in% c("f"),
         visual_stage %in% c("Blankål","Halvblank ål","Gulål")) %>%
  # with wrong classifications;
  mutate(redDurif_stage = case_when(Durif_stage %in% c("I","FII") & sex == "f" ~ "I & FII",
                                     Durif_stage %in% c("FIII") & sex == "f" ~ "FIII",
                                     Durif_stage %in% c("FIV","FV") & sex == "f" ~ "FIV & FV",
                                     #Durif_stage %in% c("I","MII") & sex == "m" ~ "m<3",
                                     .default = Durif_stage)) %>%
  summarise(n = n(), .by = c(Durif_stage,visual_stage)) %>% arrange(visual_stage)
#a0 <- 
  sb_ind3 %>%
  drop_na(Durif_stage,visual_stage,sex) %>%
  filter(sex %in% c("f"),
         visual_stage %in% c("Blankål","Halvblank ål","Gulål")) %>%
  # with wrong classifications;
  mutate(redDurif_stage = case_when(Durif_stage %in% c("I","FII") & sex == "f" ~ "I & FII",
                                     Durif_stage %in% c("FIII") & sex == "f" ~ "FIII",
                                     Durif_stage %in% c("FIV","FV") & sex == "f" ~ "FIV & FV",
                                     Durif_stage %in% c("MII") ~ "I & FII",
                                     .default = Durif_stage)) %>%
  # With a possible solution assuming sex info is correct
  # mutate(condensed_stage = case_when(Durif_stage %in% c("I","FII","MII") & sex == "f" ~ "fpre3",
  #                                    Durif_stage %in% c("FIII") & sex == "f" ~ "f3",
  #                                    Durif_stage %in% c("FIV","FV") & sex == "f" ~ "fpost3",
  #                                    Durif_stage %in% c("I","MII","FII") & sex == "m" ~ "mpre3",
  #                                    Durif_stage %in% c("FIII","FV") & sex == "m" ~ "m3",
  #                                    .default = Durif_stage)) %>%
  
  ggplot() +
  geom_density(aes(length1, color = redDurif_stage)) +
  geom_density(aes(length1, fill = visual_stage), alpha = 0.5, color = NA) +
  #geom_density(aes(length1, fill = visual_stage), color = NA, alpha = 0.2) +
  #scale_fill_viridis_d() +
  facet_wrap(~sex, scales = "free")
```


```{r}
a <- sb_ind3 %>%
  drop_na(Durif_stage,sex) %>%
  filter(sex %in% c("f")) %>%
  # with wrong classifications;
  mutate(condensed_stage = case_when(Durif_stage %in% c("I","FII") & sex == "f" ~ "f<3",
                                     Durif_stage %in% c("FIII") & sex == "f" ~ "f3",
                                     Durif_stage %in% c("FIV","FV") & sex == "f" ~ "f>3",
                                     Durif_stage %in% c("I","MII") & sex == "m" ~ "m<3",
                                     .default = Durif_stage)) %>%
  # With a possible solution assuming sex info is correct
  # mutate(condensed_stage = case_when(Durif_stage %in% c("I","FII","MII") & sex == "f" ~ "fpre3",
  #                                    Durif_stage %in% c("FIII") & sex == "f" ~ "f3",
  #                                    Durif_stage %in% c("FIV","FV") & sex == "f" ~ "fpost3",
  #                                    Durif_stage %in% c("I","MII","FII") & sex == "m" ~ "mpre3",
  #                                    Durif_stage %in% c("FIII","FV") & sex == "m" ~ "m3",
  #                                    .default = Durif_stage)) %>%
  
  ggplot() +
  geom_density(aes(length1, color = condensed_stage), alpha = 0.5) +
  #geom_density(aes(length1, fill = visual_stage), color = NA, alpha = 0.2) +
  #scale_fill_viridis_d() +
  facet_wrap(~sex, scales = "free")

a2 <- sb_ind3 %>%
  drop_na(Durif_stage,sex) %>%
  filter(sex %in% c("f","m")) %>%
  # With a possible solution assuming sex info is correct
  mutate(condensed_stage = case_when(Durif_stage %in% c("I","FII","MII") & sex == "f" ~ "fpre3",
                                     Durif_stage %in% c("FIII") & sex == "f" ~ "f3",
                                     Durif_stage %in% c("FIV","FV") & sex == "f" ~ "fpost3",
                                     Durif_stage %in% c("I","MII","FII") & sex == "m" ~ "mpre3",
                                     Durif_stage %in% c("FIII","FV") & sex == "m" ~ "m3",
                                     .default = Durif_stage)) %>%
  ggplot() +
  geom_histogram(aes(length1, color = condensed_stage), alpha = 0.5) +
  # geom_density(data = sb_ind3 %>% filter(!(is.na(Durif_stage) & is.na(visual_stage)),
  #                                        sex %in% c("f","m")), aes(length1, fill = visual_stage), color = NA, alpha = 0.2) +
  geom_histogram(data = sb_ind3 %>% filter(!(is.na(Durif_stage) & is.na(visual_stage) & is.na(sex)),
                                         sex %in% c("f","m")), aes(length1, fill = visual_stage), color = NA, alpha = 0.2) +
  #scale_fill_viridis_d() +
  facet_wrap(~sex, scales = "free") 

b <- sb_ind3 %>% 
  drop_na(Durif_stage,sex) %>%
  filter(sex %in% c("f","m")) %>%
  ggplot() +
  #geom_density(aes(length1, color = condensed_stage), alpha = 0.5) +
  geom_density(aes(length1, color = visual_stage), alpha = 0.4) +
  #scale_fill_viridis_d() +
  facet_wrap(~sex, scales = "free") 

a/b
a2/b

sb_ind3 %>%
  drop_na(Durif_stage) %>%
  filter(sex %in% c("m"),
         length1 > 450)
  
sb_ind3 %>% filter(!(is.na(Durif_stage) & is.na(visual_stage)),
                   sex %in% c("f","m"),
                   #visual_stage == "Gulål") 
                   visual_stage == "Blankål")

#   #HöBr,VäBr,HöH,HöV,VäH,VäV, Note length1 is in mm - dividing with 10.
#   mutate(eye_index = 100*(pi*((VäH + VäV)/4)^2) / (length1),
#          fin_index = (VäBr / length1) * 100,
#          is_silver = case_when(eye_index >= 6.5 ~ "Silver",
#                                eye_index < 6.5  ~ "Yellow/Resident",
#                                TRUE             ~ "Unknown"),
#          durif_stage = case_when(
#            # Stage I: Small, immature yellow eels
#            BL < 45 & eye_index < 6.5 ~ "I",
#            # Stage II: Larger growth phase, still yellow
#            BL >= 45 & eye_index < 6.5 ~ "II",
#            # Stage III: Pre-migrant/Transitional phase
#            eye_index >= 6.5 & eye_index < 8.0 & fin_index < 4.5 ~ "III",
#            # Stage IV: Migrating phase (Silvering)
#            eye_index >= 8.0 & fin_index >= 4.5 & fin_index < 5.0 ~ "IV",
#            # Stage V: Advanced migrating phase
#            eye_index >= 8.0 & fin_index >= 5.0 ~ "V",
#            # Catch-all for data outside typical ranges
#           TRUE ~ "Indeterminate"))

```

### KUL

```{r}
# Connect to SLU-server:
# AQ_con <- dbConnect(odbc(),
#                     Driver = "ODBC Driver 18 for SQL Server",
#                     Server = "aquadw_prod.db.slu.se",
#                     USER = "vitl0001", # set you name
#                     Database = "AquaDW_prod",
#                     Trusted_Connection = "yes",
#                     Encrypt = "no",
#                     encoding = "utf-8")
#  
# # Extract the table with all individual eel data.
#  
# KUL <- dbGetQuery(AQ_con,"select * from AquaDW_prod.mart.KUL_INDIVID_NEW where Art = 'Ål'")
# saveRDS(KUL, file = paste0( "/Users/vitl0001/Documents/Projects/SWEel-lhts/data/KUL_",Sys.Date(),".RData"))
kul_ind <- readRDS("/Users/vitl0001/Documents/Projects/SWEel-lhts/data/KUL_2026-05-04.RData")
colnames(kul_ind)
#kul_ind %>% 
  #filter(InsamlMetod == "Fiskmärkning"),
  #       Årtal1 != Årtal2)
  #mutate(n = n(), .by = Ind_id) %>%
  #filter(n > 1)
  #mutate(ismark = if_else(n > 1, 1,0)) %>%
  #summarise(n = n(), .by = c(ismark)) 
  #summarise(n = n(), .by = c(InsamlMetod)) %>%
  #summarise(n = n(), .by = c(Märkning)) %>%
#arrange(-n)
  #distinct(Redskap)

kul_ind2 <- kul_ind %>% 
  filter(!(is.na(Slutlängd_cm) & is.na(Totalvikt_gram) & is.na(Ålder))) %>%
  rename(length1 = Slutlängd_mm,
         weight1 = Totalvikt_gram,
         #  weight2 = Vikt2,
         age = Ålder,
         sex = Kön,
         visual_stage = Artbestämning,
         year = Fiskeår
         ) %>%
  mutate(lon = Bäst_longitud_decimal_grader,
         lat = Bäst_latitud_decimal_grader,
         db = "kul")
```
<!-- Error in `dbConnect()`: -->
<!-- ! ODBC failed with error 00000 from [unixODBC][Driver Manager]. -->
<!-- ✖ Can't open lib 'SQL Server' : file not found -->
<!-- ℹ From nanodbc/nanodbc.cpp:1184. -->
<!-- Run `rlang::last_trace()` to see where the error occurred. -->

## Join data
```{r}
# can there be dupes between the dbs?
dupes <- c(kul_ind$Ind_id,sb_ind2$IndividID)[duplicated(c(kul_ind$Ind_id,sb_ind2$IndividID))]
kul_ind2 %>%
  filter(Ind_id %in% dupes) %>% select(length1, age,db) %>% bind_cols(sb_ind2 %>% filter(IndividID %in% dupes) %>% select(length1,age,db)) # likely not

# join the sb and kul data
#cols <- c("length1","length2","weight1","weight2","age","lat","lon","sex","stage","db","year")
cols <- c("length1","weight1","age","lat","lon","sex","visual_stage","Durif_stage","db","year")
df <- sb_ind3 %>% 
  select(all_of(cols), VattenNamn) %>% 
  bind_rows(kul_ind2 %>% 
            mutate(Durif_stage = NA) %>%
            select(all_of(cols), Lokal)) %>%
  mutate(sex = ifelse(sex %in% c("f","Hona"), "female", 
                      if_else( sex %in% c("m","Hane"), "male", NA)),
         ind_id = row_number())

```

## Retrieve spatial info

```{r}
# make data spatial object
df_sf <- st_as_sf(df %>% drop_na(lat,lon), coords = c("lon", "lat"), crs = 4326,  remove = FALSE)

re <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/refeel/", format = "parquet")
ca <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/catchments/", format = "parquet")

# refeel countries
co_sf <- re %>%
  collect() %>%
  filter(are_lev_code %in% "Country") %>%
  mutate(geometry = st_as_sfc(geom_polygon), crs = 4326) %>%
  st_as_sf(sf_column_name = "geometry", crs = 4326)

# join in country info and drop non SE data points
df_co <- df_sf %>%
  st_join(co_sf %>% select(are_code), join = st_nearest_feature) %>%
  rename(country = are_code) %>%
  filter(country == "SE")

plot_map_Nord +
  geom_point(data = df_co %>% st_drop_geometry() %>% add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000, color = country), size = 0.1)

# main catchments / basins / HARO
ca_sf <- ca %>%
  collect() %>%
  mutate(geometry = st_as_sfc(shape, EWKB = TRUE, crs = 4326),
         main_bas = main_bas) %>%
  st_as_sf(sf_column_name = "geometry") %>%
  select(main_bas) %>%
  group_by(main_bas) %>%
  summarise() %>%
  ungroup()

plot_map_Nord +
  geom_sf(data = ca_sf)

# add in catchments to sötebasen data
df_coca_sb <- df_co %>%
  filter(db == "sb") %>%
  st_join(ca_sf, join = st_intersects)

# those without main_bas
df_coca_sb %>% filter(is.na(main_bas)) %>%
  st_drop_geometry() %>%
  distinct(VattenNamn)

# Fix Dalälven to have the same main_bas as the other Dalälven
dal_mb <- df_coca_sb %>% filter(VattenNamn == "Dalälven" & !is.na(main_bas)) %>% distinct(main_bas) %>% pull()

df_coca_sb <- df_coca_sb %>%
  mutate(main_bas = if_else(VattenNamn == "Dalälven", dal_mb, main_bas)) 

df_coca_sb %>%  
filter(is.na(main_bas)) %>%
  distinct(VattenNamn)
# 
# plot_map_Nord +
#   geom_point(data = df_ca %>% filter(!is.na(main_bas)) %>% st_drop_geometry() %>% add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000), color = "red",size = 0.1) +
#   geom_point(data = df_ca %>% filter(is.na(main_bas)) %>% st_drop_geometry() %>% add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000), size = 0.1)

# join the sb and kul spatial units data

df_all <- df_coca_sb %>%
  mutate(spat.unit = if_else(is.na(main_bas), VattenNamn, as.character(main_bas))) %>%
  bind_rows(df_co %>%
              filter(db == "kul") %>%
              mutate(spat.unit = as.character(Lokal))) %>%
  as_tibble()

# select the basins with data for plotting the catchments
ca_sf2 <- ca_sf %>%
  filter(main_bas %in% df_coca_sb$main_bas)
```

## Data points in space and catchments
```{r}
plot_map_Nord +
  geom_sf(data = ca_sf2, aes(fill = factor(main_bas)), color = NA,  alpha = 0.3)  +
  geom_point(data = df_all %>% 
               add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000, color = db), size = 0.1) 
  #guides(color = guide_legend(title.position = "top"))
  # scale_fill_viridis_d() +
  # scale_color_viridis_d()

```

## Save data
```{r}
saveRDS(df_all %>% st_drop_geometry(), file = paste0(home, "/data/sweel_data_",Sys.Date(),".RData"))
```

