---
title: "Swedish eel silvering model summary"
subtitle: "SWEELHT"
author: "Viktor Thunell" 
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    code-fold: true
    code-summary: "Show code"
    page-layout: full
    embed-resources: true
    toc: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 80%
editor: source
execute: 
  echo: true
  eval: true
  cache: true
---

## Load libraries

```{r}
#| message: false
#| warning: false
#| cache: false

# Load libraries, install if needed
pkgs <- c("tidyverse", "tidylog", "devtools","viridis","sf","patchwork","posterior", "tidybayes","bayesplot","nimble","here","reshape2","sdmTMB")

if(length(setdiff(pkgs,rownames(installed.packages()))) > 0){
    install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
  }

invisible(lapply(pkgs, library, character.only = T))

devtools::source_url("https://raw.githubusercontent.com/VThunell/diasp-lht/main/R/functions/map-plot.R")
options(ggplot2.continuous.colour = "viridis")
theme_set(theme_minimal()) 

# Set path
home <- here::here()
```

## Read data

```{r}
#| message: false
#| warning: false
#| cache: false

## Read data
sweels <- readRDS(file = paste0(home, "/data/sweel_data_2026-05-28.RData"))
```

## Silvering logsitic regression model

### Define data

```{r}
# df.sweel2 <- sweels %>%
#   drop_na(length1) %>%
#   filter(visual_stage %in% c("Blankål","Halvblank ål","Gulål"),
#          country == "SE") %>%
#   mutate(silver = case_when(visual_stage == "Blankål" ~ 1,
#                             visual_stage == "Halvblank ål" ~ NA,
#                             visual_stage == "Gulål" ~ 0,
#                             .default = NA),
#          silver = as.integer(silver),
#          length_sc = (length1 - mean(length1)) / sd(length1),
#          mb = as.integer(factor(main_bas)),
#          sex = as.integer(if_else(sex == "female", 0, 1)),
#          ind.id = row_number())

df.sweel3 <- sweels %>%
  # remove rows where used variables have at least two non NAs
  filter(rowSums(!is.na(select(., visual_stage, Durif_stage, weight1, length1,age))) >= 2,
  #filter(visual_stage %in% c("Blankål","Halvblank ål","Gulål","Yngel"),
         !(is.na(visual_stage) & is.na(Durif_stage)),
         sex == "female") %>% 
  mutate(silver_vis = case_when(visual_stage == "Blankål" ~ 1,
                                visual_stage == "Halvblank ål" ~ NA,
                                visual_stage %in% c("Gulål","Yngel","Juvenil") ~ 0,
                                .default = NA),
         silver_dur = case_when(Durif_stage %in% c("I","FII","MII") ~ 0,
                                Durif_stage %in% c("FIII") ~ NA,
                                Durif_stage %in% c("FIV","FV") ~ 1,
                                .default = NA),
         length_sc = (length1 - mean(length1)) / sd(length1),
         age_sc = (age - mean(age, na.rm = TRUE)) / sd(age, na.rm = TRUE),
         su = as.integer(factor(spat.unit)),
         ind.id = row_number())

df.sweel3 %>%
  distinct(silver_vis,silver_dur)

df.sweel3 %>%
  st_drop_geometry() %>%
  summarise(count = n(), .by = c(su)) %>% arrange(-count)

```

### Plot silvering data
```{r}
# length at age by stage and sex
df.sweel3 %>%
  ggplot(aes(age, length1, color = factor(sex))) +
  geom_point(size = 0.1, alpha = 0.3) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4), show.legend = FALSE) 
  facet_wrap(~visual_stage) +
  theme_minimal()

df.sweel3 %>%
  ggplot(aes(age, length1, color = factor(sex))) +
  geom_point(size = 0.1, alpha = 0.3) +
  facet_wrap(~Durif_stage) +
  theme_minimal()

# relationship between age and silver
df.sweel3 %>%
  mutate(silv = silver_vis * silver_dur,
         silv = if_else(is.na(silv), 0.5, silv)) %>%
  ggplot(aes(silv, age)) +
  geom_point(size = 0.1, alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal()
  
# relationship between length and silver
df.sweel3 %>%
  mutate(silv = silver_vis * silver_dur,
         silv = if_else(is.na(silv), 0.5, silv)) %>%
  ggplot(aes(silv, length1)) +
  geom_point(size = 0.1, alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal()

# length of the silvers (where one of the classifiers says it is silver)
df.sweel3 %>%
  mutate(silver_dur = if_else(is.na(silver_dur),-1,silver_dur),
         silver_vis = if_else(is.na(silver_vis),-1,silver_vis),
         silv = silver_dur+silver_vis) %>%
  filter(!silv < 0) %>%
  ggplot(aes(length1, factor(su), color = db)) +
  geom_boxplot(outlier.color = "grey",
               outlier.size = 0.5) 

# length-weight
df.sweel3 %>%
  drop_na(length1,weight1) %>%
  ggplot(aes(length1, weight1,color = factor(silver_dur))) +
  geom_point(size = 0.1, alpha = 0.3) 
    
```
### n over space and time 

```{r}
df.sweel3 %>%
  summarise(count = n(), .by = c(su))

df.sweel3 %>%
  summarise(count = n(), .by = c(year, su)) %>%
  ggplot(aes(year, factor(su), fill = count)) +
  geom_tile(color = "gray30") +
  #geom_vline(xintercept = 1998, color = "darkgrey") +
  scale_fill_viridis_c() +
  labs(y = "", x = "year") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### Source models / Load samples
```{r, cache = FALSE}
# Load samples
sweelsilv_m1.samples <- readRDS(paste0(home,"/data/samples/sweelsilv.samples_2026-05-27.RData"))$samples # v9

sweelsilv.samples$WAIC 
# for simple 33029.01 - 20260507
# for spatial alpha 13956.79 - 20260507  
# for spatial and hierachical alpha 13875.92 - 20260508
# for spatial b0 and hierachical spatial alpha 13570.31 - 20260508
# for spatial and hierachical alpha and b0 13506.59 - 20260511
# for spatial and hierachical alpha and b0 21417.19 - 20260511 (this adds data som incomparable to previous models)
# for spatial and hierachical alpha and b0 with two classifiers and se/sp: 8411.084


s.samples <- sweelsilv.samples$samples 
# # Or source model code and mcmc (load libs and data)
# t <- Sys.time()
# source(file = paste0(home,"/models_eel/model_eel_silvering.R"))
# Sys.time() - t # approx 4.5 hours with 10000 hmc samples


```

### Traces, ess, and ‘potential scale reduction factor’

Variables "s.sig","Ustar","U","mu.a.gl","sd.a.gl","alpha","bs","bt")
```{r, cache = FALSE}
as_draws(s.samples) %>% variable.names()
node.sub <- subset_draws(as_draws(s.samples), variable = c("alpha"))
node.sub[,sample(1:dim(node.sub)[2], 16)] %>% mcmc_trace() # one chain
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) 

node.sub <- subset_draws(as_draws(s.samples), variable = c("log_b0"))
node.sub[,sample(1:dim(node.sub)[2], 16)] %>% mcmc_trace() # one chain
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail"))

node.sub <- subset_draws(as_draws(s.samples), variable = c("b1"))
node.sub <- subset_draws(as_draws(s.samples), variable = c("sp_v","sp_d","se_v","se_d"))
#node.sub <- subset_draws(as_draws(s.samples), variable = c("sp_d","se_d"))
#node.sub[,,sample(1:dim(node.sub)[3], 16)] %>% mcmc_trace()
node.sub[] %>% mcmc_trace() # one chain
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail"))

variable.names(as_draws(s.samples)) %>%
  str_remove("\\[.*\\]") %>% unique()
node.sub <- subset_draws(as_draws(s.samples), variable = "bs")
#node.sub[,,sample(1:dim(node.sub)[3], 16)] %>% mcmc_trace()
node.sub %>% mcmc_trace() # one chain
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail"))

```

### Silvering variables

```{r}
# Compare alpha between models
s.samples %>%
  as_draws() %>%
  spread_draws(alpha[mb]) %>%
  left_join(df.sweel3 %>% distinct(mb,main_bas)) %>%
  select(alpha,main_bas) %>%
  mutate(model = "m2") %>%
  ungroup() %>%
  bind_rows(sweelsilv_m1.samples %>%
              as_draws() %>%
              spread_draws(alpha[mb]) %>%
              left_join(df.sweel2 %>% distinct(mb,main_bas)) %>%
              select(alpha,main_bas) %>%
              mutate(model = "m1") %>%
              ungroup()) %>%
  ggplot() +
  geom_density(aes(x = alpha, color = factor(model))) +
  facet_wrap(~main_bas, scales = "free_y", ncol = 3) +
  theme_minimal() 

s.samples %>%
  as_draws() %>%
  spread_draws(log_b0[mb]) %>%
  left_join(df.sweel3 %>% distinct(mb,main_bas)) %>%
  select(log_b0,main_bas) %>%
  mutate(model = "m2") %>%
  ungroup() %>%
  bind_rows(sweelsilv_m1.samples %>%
              as_draws() %>%
              spread_draws(log_b0[mb]) %>%
              left_join(df.sweel2 %>% distinct(mb,main_bas)) %>%
              select(log_b0,main_bas) %>%
              mutate(model = "m1") %>%
              ungroup()) %>%
  ggplot() +
  geom_density(aes(x = log_b0, color = factor(model))) +
  facet_wrap(~main_bas, scales = "free_y", ncol = 3) +
  theme_minimal() 

# b0
s.samples %>%
  as_draws() %>%
  spread_draws(log_b0[mb]) %>%
  #mutate(b0 = exp(log_b0)) %>%
  ggplot() +
  geom_density(aes(x = exp(log_b0), color = factor(mb))) +
  #facet_wrap(~ecoreg, scales = "free_y", ncol = 3) +
  theme_minimal() 

# L50
s.samples %>%
  spread_draws(alpha[mb], log_b0[mb]) %>%
  mutate(L50_sc = -alpha/exp(log_b0),
         L50 = L50_sc * sd(df.sweel3$length1) + mean(df.sweel3$length1)) %>%
  ggplot() +
  geom_density(aes(L50, color = factor(mb))) +
  theme_minimal() +
  xlim(0,1500)
  #xlim(-5,5)
  
 
s.samples %>%
  as_draws() %>%
  gather_draws(se_d,se_v,sp_d,sp_v) %>%
  ggplot() +
  geom_density(aes(x = .value, color = .variable)) +
  stat_function(fun = dbeta, args = list(shape1 = 1, shape2 = 9)) +
  xlim(0.8,1) +
  #facet_wrap(~ecoreg, scales = "free_y", ncol = 3) +
  theme_minimal()

```


```{r}
silv.samples[[1]] %>%
  gather_draws(alpha[er, yr], sep = ",") %>%
  ungroup() %>%
  left_join(data.silv %>% distinct(er,ecoreg)) %>%
  ggplot() +
  geom_density(aes(x = .value, color = factor(yr))) +
  facet_wrap(~ecoreg, scales = "free_y", ncol = 3) +
  theme_minimal() +
  labs(title = "alpha")

silv.samples[[1]] %>%
  gather_draws(bs[er], sep = ",") %>%
  ungroup() %>%
  left_join(data.silv %>% distinct(er,ecoreg)) %>%
  ggplot() +
  geom_density(aes(x = .value, color = ecoreg)) +
  theme_minimal() +
  labs(title = "bs")

silv.samples[[1]] %>%
  gather_draws(s.sigma,bt) %>%
  ggplot() +
  geom_boxplot(aes(x = .value, color = .variable)) +
  facet_wrap(~.variable, scales = "free") +
  theme_minimal() 

# effect of Temp in % change in length by degree Celcius
silv.samples[[1]] %>%
  gather_draws(bt) %>%
  median_qi() %>%
  mutate(eff = exp(.value / sd(data.silv$tmp_dc_uyr/10))) # Note that tmp_dc_uyr is in Celcius*10

```


### Predicted / observed

```{r}
# var.lats <- data.silv %>%
#   mutate(m.lat = mean(ser_y), .by = ecoreg) %>%
#   distinct(er, ecoreg, m.lat) %>%
#   arrange(-m.lat)

dfp <- s.samples %>%
  as_draws() %>%
  spread_draws(mu_s[ind.id]) %>%
  median_qi() %>%
  rename(pred.sl = mu_s) %>%
  ungroup() %>%
  left_join(df.sweel %>%
              select(main_bas,length1,lat,lon,sex,ind.id) %>%
              rename(obs.sl = length1))
  #left_join(var.lats) %>%
  #mutate(ecoreg = fct_reorder(as.factor(ecoreg), -m.lat))

dfp %>%
  #filter(is.na(sex)) %>%
  ggplot() +
  geom_abline(slope = 1, color = "darkgrey") +
  geom_point(aes(x = obs.sl, y = exp(pred.sl), color = sex), shape = 4, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~main_bas) +
  theme_minimal() +
  labs(y="predicted", x="observed")
#ggsave(paste0(home, "/report/silv_po.png"), width = 17, height = 14, units = "cm")


```

### logistic function p ~ length
```{r}
# using alpha, b0 which is per basin 
dfzb <- s.samples %>%
  spread_draws(alpha[mb], log_b0[mb]) %>%
  median_qi() %>%
  expand_grid(length_sc = seq(min(df.sweel3$length_sc),max(df.sweel3$length_sc), by = 0.05), sex = 0:1) %>%
  left_join(df.sweel3 %>% distinct(main_bas,mb)) %>%
  ungroup() %>%
  mutate(p_mean = 1 / (1 + exp(-(alpha + exp(log_b0)*length_sc))))

smb <- sample(df.sweel3$mb, 16, replace = FALSE)
dfzb %>%
  filter(sex == 0,
         mb %in% smb) %>%
  ggplot() +
  geom_line(aes(x = length_sc, y = p_mean, color = factor(main_bas)), show.legend = FALSE) +
  geom_point(data = df.sweel3 %>% filter(sex == 0,mb %in% smb), aes(length_sc, y = silver_dur, color = factor(main_bas)),show.legend = FALSE, alpha = 0.3) 
  facet_wrap(~main_bas) 

dfzb %>%
  filter(sex == 0) %>%
  ggplot() +
  geom_line(aes(x = length_sc, y = p_mean, color = factor(main_bas)), show.legend = FALSE)
```

```{r}
dfp <- silv.samples %>%
  spread_draws(s.mu[i]) %>%
  left_join(data.silv %>% 
              select(ecoreg,sex,fi_year) %>% 
              mutate(i = row_number()), 
            by = "i") %>%
  group_by(.draw, ecoreg, sex, fi_year) %>%
  summarise(pred.sl = median(s.mu), .groups = "drop") %>%
  left_join(var.lats) %>%
  mutate(ecoreg = fct_reorder(as.factor(ecoreg), m.lat),
         sex = if_else(sex == 0, "female", "male")) %>%
  mutate(m_pred = median(pred.sl), .by = c(sex))

n.labs <- data.silv %>%
  summarise(n = n(), .by = c(ecoreg, sex)) %>%
  mutate(sex = if_else(sex==1, "female", "male"))

dfp %>% summarise(mexp = exp(median(pred.sl)), .by= sex)
dfp %>% ungroup() %>% summarise(exp(median(pred.sl)), .by= sex)

dfp %>%
  ggplot() +
  geom_boxplot(aes(x = exp(pred.sl), y = ecoreg), outliers = FALSE, show.legend = FALSE) +
  geom_vline(aes(xintercept = exp(m_pred)), color = "darkgrey", size = 0.5) +
  facet_wrap(~sex, scales = "free_x") +
  theme_minimal() +
  labs(x = "Length at silvering [mm]", y = "ecoregion")
ggsave(paste0(home, "/report/silv_ERl.png"), width = 17, height = 14, units = "cm")

```

### Length over space
```{r, cache = FALSE}
# L50 by points
dfs <- s.samples %>%
  as_draws() %>%
  spread_draws(alpha[mb], log_b0[mb], sep = ",") %>%
  median_qi() %>%
  mutate(L50 = -alpha/exp(log_b0)) %>%
  # gather_draws(alpha[mb], bs[er], bt, sep = ",") %>%
  left_join(df.sweel2 %>% distinct(main_bas,mb,lat,lon))# %>%

# by catchment  
dfsca <- ca_sf2 %>%
  #mutate(main_bas = as.factor(main_bas)) %>%
  left_join(dfs %>% distinct(mb,L50,main_bas)) %>%
  filter(!is.na(mb)) #%>%
  mutate(pred.length = exp(.value))
  
plot_map_Nord +
  geom_sf(data = dfsca, aes(fill = L50), color = NA,  alpha = 0.5) +
  scale_fill_viridis_c() +
  geom_point(data = df.sweel2 %>% drop_na(lat,lon) %>% 
               add_utm_columns(ll_names = c("lon", "lat"), utm_crs = 32633), aes(X*1000, Y*1000), #color = , 
             size = 0.1) 
  
# # ungroup() %>%
#   # mutate(female = alpha + bt*mt,
#   #        male = alpha + bs + bt*mt,
#   #        year = yr + 1997) %>%
#   pivot_longer(cols = c("female","male"), names_to = "sex", values_to = "length") %>%
#   mutate(length = exp(length)) %>%
#   mutate(m_length = median(length), .by = c(year,sex)) %>%
#   left_join(var.lats) %>%
#   mutate(ecoreg = fct_reorder(ecoreg, -m.lat)) 
# 
# dfp %>%
#   filter(sex == "female") %>%
#   ggplot() +
#   geom_boxplot(aes(y = length, x = year, group = year), color = "#F8766D", outliers = FALSE) +
#   geom_line(aes(y = m_length, x = year), color = "#F8766D", alpha = 0.4) +
#   facet_wrap(~ecoreg, scales = "free_y") +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, size = rel(.75))) +
#   labs(x = "year")
# ggsave(paste0(home, "/report/silv_lf.png"), width = 17, height = 14, units = "cm")
# 
# dfp %>%
#   filter(sex == "male") %>%
#   ggplot() +
#   geom_boxplot(aes(y = length, x = year, group = year), color = "#00BFC4", outliers = FALSE) +
#   geom_line(aes(y = m_length, x = year), color = "#00BFC4", alpha = 0.4) +
#   facet_wrap(~ecoreg, scales = "free_y") +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, size = rel(.75))) +
#   labs(x = "year")
# ggsave(paste0(home, "/report/silv_lm.png"), width = 17, height = 14, units = "cm")  

```

### Correlation/covariance matrix
```{r}
# median sample correlation 
samp <- silv.samples[[1]]

cols <- grep("^R",colnames(as.matrix(samp)))

ner <- length(unique(data.silv$ecoreg))

corr_arr <- array(NA, dim = c(ner, ner, nrow(samp)))

for (i in 1:nrow(samp)) {

  R_sample <- matrix(
    as.numeric(samp[i, cols]),
    nrow = ner,
    ncol = ner,
    byrow = FALSE
  )

  corr_arr[, , i] <- crossprod(R_sample)
}

corr <- apply(corr_arr, c(1, 2), median)

er.labs <- var.lats %>%
  select(er, ecoreg) %>%
  { setNames(.$ecoreg, .$er) }

as.data.frame(corr) %>%
  mutate(r = row_number()) %>%
  pivot_longer(cols = -r, names_to = "c", values_to = "value") %>%
  mutate(c = as.integer(gsub("V", "", c)) ) %>%
  left_join(var.lats, by = c("r" = "er")) %>%
  left_join(var.lats, by = c("c" = "er"), suffix = c(".x", ".y")) %>%
  mutate(r = reorder(r, m.lat.x),
         c = reorder(c, -m.lat.y)) %>%
  ggplot(aes(x=c, y=r, fill = value)) + 
  geom_tile() +
  scale_fill_viridis_c() +
  scale_x_discrete(labels = er.labs) +
  scale_y_discrete(labels = er.labs) +
  theme(axis.text = element_text(angle = 45, hjust = 1, size = rel(.75))) +
  labs(x = "", y = "")
ggsave(paste0(home, "/report/silv_cor.png"), width = 17, height = 14, units = "cm")  
```